version: "3.8"

services:
  # mariadb:
  #   image: mariadb:10.7.3
  #   container_name: checkin-mariadb
  #   restart: always
  #   ports:
  #     - "15666:3306"
  #   environment:
  #     TZ: Asia/Shanghai
  #     MYSQL_ROOT_PASSWORD: HC8NjpCgBWM08Vor3Niv # 设置 root 用户的密码
  #     MYSQL_DATABASE: checkin # 初始化的数据库名称
  #     MYSQL_USER: checkin # 创建的用户
  #     MYSQL_PASSWORD: 123456 # 用户的密码
  #   networks:
  #     - my_network
  #   volumes:
  #     - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
  #     - ./docker/mysql/conf.d:/etc/mysql/conf.d
  #     - ./docker/mysql/data:/var/lib/mysql # 数据持久化

  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: checkin-app
    restart: unless-stopped
    ports:
      - "7788:7788"
    environment:
      TZ: Asia/Shanghai
      STORAGE: mysql
      SQLITE_PATH: "./db/checkin.db"
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DB_NAME: "${DB_DATABASE}"
      REPORT_API: "http://${APP_IPPR}.3:80/api/public/checkin/report"
      REPORT_KEY: "2fc24d61be12502d4414503efb48308f"
    volumes:
      - ./docker/sqlite:/app/db
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.55"

networks:
  extnetwork:
    name: "dootask-networks-${APP_ID}"
    external: true