// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	CheckinDevice       *checkinDevice
	CheckinDeviceRecord *checkinDeviceRecord
	CheckinDeviceUser   *checkinDeviceUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CheckinDevice = &Q.CheckinDevice
	CheckinDeviceRecord = &Q.CheckinDeviceRecord
	CheckinDeviceUser = &Q.CheckinDeviceUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		CheckinDevice:       newCheckinDevice(db, opts...),
		CheckinDeviceRecord: newCheckinDeviceRecord(db, opts...),
		CheckinDeviceUser:   newCheckinDeviceUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CheckinDevice       checkinDevice
	CheckinDeviceRecord checkinDeviceRecord
	CheckinDeviceUser   checkinDeviceUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		CheckinDevice:       q.CheckinDevice.clone(db),
		CheckinDeviceRecord: q.CheckinDeviceRecord.clone(db),
		CheckinDeviceUser:   q.CheckinDeviceUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		CheckinDevice:       q.CheckinDevice.replaceDB(db),
		CheckinDeviceRecord: q.CheckinDeviceRecord.replaceDB(db),
		CheckinDeviceUser:   q.CheckinDeviceUser.replaceDB(db),
	}
}

type queryCtx struct {
	CheckinDevice       ICheckinDeviceDo
	CheckinDeviceRecord ICheckinDeviceRecordDo
	CheckinDeviceUser   ICheckinDeviceUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CheckinDevice:       q.CheckinDevice.WithContext(ctx),
		CheckinDeviceRecord: q.CheckinDeviceRecord.WithContext(ctx),
		CheckinDeviceUser:   q.CheckinDeviceUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
